server:
  port: 8980
spring:
  application:
    name: API-ADMINS
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.99.221:3306/yingxue?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456