version: "3.9"

services:
  nacos:
    image: nacos/nacos-server:2.0.2
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"



#  admins:
#    build:
#      context: ./images/admins
#      dockerfile: Dockerfile
#    ports:
#      - "8980:8980"
#    depends_on:
#      - mysql
#      - nacos
#      - redis
#
#  admins01:
#    build:
#      context: ./images/admins
#      dockerfile: Dockerfile
#    ports:
#      - "8988:8980"
#    depends_on:
#      - mysql
#      - nacos
#      - redis
#
#  category:
#    build:
#      context: ./images/category
#      dockerfile: Dockerfile
#    ports:
#      - "8981:8981"
#    depends_on:
#      - mysql
#      - nacos
#      - redis
#
#  gateway:
#    build:
#      context: ./images/gateway
#      dockerfile: Dockerfile
#    ports:
#      - "9999:9999"
#    depends_on:
#      - mysql
#      - nacos
#      - redis
#
#  users:
#    build:
#      context: ./images/users
#      dockerfile: Dockerfile
#    ports:
#      - "8982:8982"
#    depends_on:
#      - mysql
#      - nacos
#      - redis
#
#  videos:
#    build:
#      context: ./images/videos
#      dockerfile: Dockerfile
#    ports:
#      - "8983:8983"
#    depends_on:
#      - mysql
#      - nacos
#      - redis
#
#  nginx:
#    image: nginx:1.21.1
#    ports:
#      - "80:80"
#    volumes:
#      - ./admin-dist:/usr/share/nginx/html:ro
