server:
  port: 9999
spring:
  application:
    name: API-GATEWAY
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

    gateway:
      routes: #用来配置路由规则
      #admin routers
        - id: admin_routers
          uri: lb://API-ADMINS
          predicates:
            - Path: /admin/**


